/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Usuario
 */
public class aVistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form aVistaPrincipal
     */
    public aVistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMadministracion = new javax.swing.JMenu();
        jMinicioAdmin = new javax.swing.JMenuItem();
        jMAgregar = new javax.swing.JMenu();
        jMagregarReservas = new javax.swing.JMenuItem();
        jMreserva = new javax.swing.JMenu();
        jMreservas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jMadministracion.setText("Administracion");
        jMadministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMadministracionActionPerformed(evt);
            }
        });

        jMinicioAdmin.setText("Inicio admin.");
        jMinicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinicioAdminActionPerformed(evt);
            }
        });
        jMadministracion.add(jMinicioAdmin);

        jMenuBar1.add(jMadministracion);

        jMAgregar.setText("Agregar");

        jMagregarReservas.setText("Agregar Reserva");
        jMagregarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMagregarReservasActionPerformed(evt);
            }
        });
        jMAgregar.add(jMagregarReservas);

        jMenuBar1.add(jMAgregar);

        jMreserva.setText("Reserva");
        jMreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMreservaActionPerformed(evt);
            }
        });

        jMreservas.setText("Reservas Totales");
        jMreservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMreservasActionPerformed(evt);
            }
        });
        jMreserva.add(jMreservas);

        jMenuBar1.add(jMreserva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMadministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMadministracionActionPerformed

    }//GEN-LAST:event_jMadministracionActionPerformed

    private void jMagregarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMagregarReservasActionPerformed
            Vista_Inicio vistaalumno = new Vista_Inicio();
            escritorio.add(vistaalumno);
            vistaalumno.setVisible(true);
    }//GEN-LAST:event_jMagregarReservasActionPerformed

    private void jMreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMreservaActionPerformed
  
    }//GEN-LAST:event_jMreservaActionPerformed

    private void jMinicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinicioAdminActionPerformed
            Vista_Inicio vistaalumno = new Vista_Inicio();
            escritorio.add(vistaalumno);
            vistaalumno.setVisible(true);
            
    }//GEN-LAST:event_jMinicioAdminActionPerformed

    private void jMreservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMreservasActionPerformed
            Vista_Inicio vistaalumno = new Vista_Inicio();
            escritorio.add(vistaalumno);
            vistaalumno.setVisible(true);
    }//GEN-LAST:event_jMreservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aVistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aVistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMAgregar;
    private javax.swing.JMenu jMadministracion;
    private javax.swing.JMenuItem jMagregarReservas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMinicioAdmin;
    private javax.swing.JMenu jMreserva;
    private javax.swing.JMenuItem jMreservas;
    // End of variables declaration//GEN-END:variables
}
